import Head from "next/head";
import Image from "next/image";
import { Inter } from "@next/font/google";
import Link from "next/link";

import me from "../assets/img/me.png";
import github from "../assets/img/github.png";
import twitter from "../assets/img/twitter.png";
import linkedin from "../assets/img/linkedin.png";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Obisike Treasure Chimeziri</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="fixed top-0">
        <nav className="fixed top-0 w-full px-[5%] mt-4">
          <div className="flex justify-between">
            <div className=" text-lg font-extrabold">OTREX</div>
            <div className="text-white md:block hidden">
              <ul className="nav">
                <li>
                  <Link href={"/about-me"}>About Me</Link>
                </li>
                <li>
                  <Link href={"/skills"}>Skills</Link>
                </li>
                <li>
                  <Link href={"/blogs"}>Blogs</Link>
                </li>
                <li>
                  <Link href={"/message-me"}>Message-me</Link>
                </li>
              </ul>
            </div>
          </div>
        </nav>
        <div className="flex flex-row">
          <div className="md:w-1/2 h-[100vh] w-full md:bg-slate-100">
            <div className="flex h-full px-[10%] items-center">
              <div>
                <h2 className="md:text-[2.5rem] italic font-mono">
                  {"\u{1F44B}"} Hello, I'm{" "}
                </h2>
                <h1 className="md:text-[4.5rem] text-[2.5rem] font-bold leading-tight">
                  Obisike Treasure
                </h1>
                <h3 className="md:text-[1.6rem] text-[1rem]">
                  A full-stack software developer and Technical Writer with
                  extensive experience developing high-performance applications.{" "}
                </h3>
                <button className="accent-btn">
                  <Link href={"/about-me"}>Get To Know Me!!{" \u{1F60A}"}</Link>
                </button>
                <button className="accent-btn-lite">
                  <Link href={"/about-me"}>Hire Me!! {"🤝🏼"}</Link>
                </button>
                <div className="flex flex-row mt-5 gap-2">
                  <div>
                    <a href="https://github.com/otrex" target="_blank">
                      <Image src={github} width={32} />
                    </a>
                  </div>
                  <div>
                    <a href="https://twitter.com/obisiket" target="_blank">
                      <Image src={twitter} width={32} />
                    </a>
                  </div>
                  <div>
                    <a href="https://linkedin/in/otrex" target="_blank">
                      <Image src={linkedin} width={32} />
                    </a>
                  </div>
                </div>
              </div>
            </div>
          </div>
          <div className="md:w-1/2 w-auto h-[100vh] absolute -z-10 flex md:block md:static bg-slate-100 md:bg-transparent">
            <Image
              src={me}
              alt="about me"
              className=" blur-2xl md:blur-none max-w-max md:max-w-full"
            />
          </div>
        </div>
      </main>
    </>
  );
}
